import type { Metadata } from "next";
import {Inter} from "next/font/google";
import  "./globals.css";

import ReactQueryProvider from "./react-query-provider/page";
import Proveiders from "./providers";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}><ReactQueryProvider><Proveiders>{children}</Proveiders></ReactQueryProvider></body>
    </html>
  );
}
